"""empty message

Revision ID: 15ad33604b36
Revises: 
Create Date: 2022-10-05 12:08:20.614106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15ad33604b36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=60, _warn_on_bytestring=True), nullable=True),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_table('user_logins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.String(length=255), nullable=False),
    sa.Column('login_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.admin_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_logins')
    op.drop_table('admin')
    # ### end Alembic commands ###
