"""empty message

Revision ID: c1332224547e
Revises: 15ad33604b36
Create Date: 2022-10-08 03:01:07.033820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1332224547e'
down_revision = '15ad33604b36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.String(length=255), nullable=False),
    sa.Column('heading', sa.Unicode(length=500), nullable=False),
    sa.Column('body', sa.Unicode(length=5000), nullable=False),
    sa.Column('image_link', sa.Unicode(length=1000), nullable=True),
    sa.Column('post_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.admin_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog')
    # ### end Alembic commands ###
